name: CI pipeline

on:
  - push
  - pull_request

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt
    - name: Lint
      id: lint
      run: |
        make lint

  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    outputs:
      coverage: ${{ steps.tox.outputs.coverage }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt
    - name: Test with tox
      id: tox
      run: |
        make test-all
        make coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo sed -i 's/azure\.//' /etc/apt/sources.list
        sudo apt-get update -y
        sudo apt install -y libunwind-dev
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt
        python -m pip install .
        python -m pip install sphinx sphinx-rtd-theme m2r2
    - name: Generate documentation with Sphinx
      run: |
        make docs
